name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: env

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login no Docker Hub (só quando for push e não PR)
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the FRONT image
      - name: Build Frontend image
        run: |
          docker build ./front \
            --file ./front/Dockerfile \
            --tag diogowinck/microblog-front:$(date +%s)

      # Push images only when it's a push (not a PR)
      - name: Push Front image
        if: github.event_name == 'push'
        run: docker push ${DOCKERHUB_USER}/microblog-front:latest


      # Build the BACK image
      - name: Build Backend image
        run: |
          docker build ./back \
            --file ./back/Dockerfile \
            --tag diogowinck/microblog-back:$(date +%s)

      - name: Push Back image
        if: github.event_name == 'push'
        run: docker push ${DOCKERHUB_USER}/microblog-back:latest
